### ISSUE TITLE
DER

### ISSUE THREAD

**Issue by FilhoDoan** [SBD1/2023.2-Hora-de-Aventura#1]
## Tarefa: Diagrama Entidade-Relacionamento  
Objetivo: fazer o diagrama de entidade-relacionamento

Fazer : 
- [x] DER -> @FilhoDoan , @HeBatalha , @Jagaima  
**Prazo:  19/09**
---
Revisar:
- [x] Revisar -> @Dyetrix 
**Prazo:  20/09**

**Comment by HeBatalha** [comment]
Diagrama concluído. Só falta revisar.

**Comment by arthur-suares** [comment]
Revisado
