### ISSUE TITLE
Atualização DER 

### ISSUE THREAD

**Issue by FilhoDoan** [SBD1/2023.2-Hora-de-Aventura#15]
# Descrição 
- [x] Especialização dos itens 
- [x] Pré requisito de habilidades 
- [x] Sistema de party  
- [x] Dependência de missão 
- [x] Missões primárias e secundárias  

# Observação 
- [x] Entregue: 18/11/2023
- [x] Revisado: 20/11/2023

**Comment by HeBatalha** [comment]
Atualização do DER concluída. A revisão será realizado junto com os outros documentos do projeto
