### ISSUE TITLE
Atualização MRE

### ISSUE THREAD

**Issue by HeBatalha** [SBD1/2023.2-Hora-de-Aventura#18]
# Descrição 
Atualizar o Modelo Relacional de acordo com o novo diagrama entidade-relacionamento.

## Dependências
- #15 

## Adições
- Especialização dos itens 
- Pré requisito de habilidades 
- Sistema de party  
- Dependência de missão 
- Especialização da loja

# Observação
- [ ] Entregue: dd/mm/yyyy
- [ ] Revisado: dd/mm/yyyy

**Comment by HeBatalha** [comment]
O prazo máximo estipulado para a realização dessa atividade é: 20/11/2023.

**Comment by arthur-suares** [comment]
Tá feitooo!
