### ISSUE TITLE
2ª Entrega: Normalização

### ISSUE THREAD

**Issue by FilhoDoan** [SBD1/2023.2-Hora-de-Aventura#4]
# Descrição
Fazer Normalização do trabalho 

# Objetivos
Entrega : 25/10
Revisão : 26/10  -> @FilhoDoan

**Comment by HeBatalha** [comment]
@HeBatalha,  @Jagaima, @Dyetrix. Terminamos a normalização. O arquivo em PDF está no novo diretório ArquivosAtuais. Esperamos a revisão de @FilhoDoan, depois de validado, transferiremos o arquivo à uma pasta da segunda entrega.
